# Generated by Django 3.2.15 on 2022-08-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='First_Name',
        ),
        migrations.AddField(
            model_name='contact',
            name='Last_Name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
